In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

import warnings
warnings.filterwarnings('ignore')

##  CC & AARRR( 거래 플랫폼 데이터 )

In [3]:
tb = pd.read_csv('../data/ecommerce_data.csv')

In [4]:
tb

        customer_id     join_dt          approved_dt  transaction_amt
0                 1  2019-04-02  2024-09-24 05:23:09            34.57
1                 2  2019-04-03                  NaN              NaN
2                 3  2019-04-02                  NaN              NaN
3                 4  2019-04-02  2024-10-20 14:45:53             9.93
4                 4  2019-04-02  2024-10-23 16:14:14            15.71
...             ...         ...                  ...              ...
441949        64208  2019-04-03  2024-11-25 15:55:38             7.00
441950        64208  2019-04-03  2024-11-26 21:35:41             0.57
441951        64209  2019-04-03  2024-09-08 12:15:53             0.86
441952        64209  2019-04-03  2024-10-11 12:47:38            12.14
441953        64210  2019-04-03  2024-09-04 16:39:51            17.29

[441954 rows x 4 columns]

In [5]:
tb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441954 entries, 0 to 441953
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   customer_id      441954 non-null  int64
 1   join_dt          441954 non-null  object
 2   approved_dt      407198 non-null  object
 3   transaction_amt  407198 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 13.5+ MB

1) 코호트 차팅 후 리텐션 정의

In [6]:
df = tb[tb.approved_dt.notnull()]
df['approved_dt'] = df['approved_dt'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))

In [9]:
df['transaction_week'] = df['approved_dt'].dt.to_period('W')
df['cohort_week'] = df.groupby('customer_id')['transaction_week'].transform('min')

In [15]:
# 코호트 기간 계산 
df['period'] = (df['transaction_week'] - df['cohort_week']).apply(lambda x: x.n)

In [16]:
# 코호트 테이블 생성
cohort_table =

,customer_id,join_dt,approved_dt,transaction_amt,transaction_week,cohort_week,period
0,1,2019-04-02,2024-09-24 05:23:09,34.57,2024-09-23/2024-09-29,2024-09-23/2024-09-29,0
3,4,2019-04-02,2024-10-20 14:45:53,9.93,2024-10-14/2024-10-20,2024-10-14/2024-10-20,0
4,4,2019-04-02,2024-10-23 16:14:14,15.71,2024-10-21/2024-10-27,2024-10-14/2024-10-20,1
5,4,2019-04-02,2024-10-23 16:16:50,15.71,2024-10-21/2024-10-27,2024-10-14/2024-10-20,1
8,7,2019-04-03,2024-10-11 17:49:15,10.79,2024-10-07/2024-10-13,2024-09-09/2024-09-15,4
...,...,...,...,...,...,...,...
441949,64208,2019-04-03,2024-11-25 15:55:38,7.00,2024-11-25/2024-12-01,2024-10-28/2024-11-03,4
441950,64208,2019-04-03,2024-11-26 21:35:41,0.57,2024-11-25/2024-12-01,2024-10-28/2024-11-03,4
441951,64209,2019-04-03,2024-09-08 12:15:53,0.86,2024-09-02/2024-09-08,2024-09-02/2024-09-08,0
441952,64209,2019-04-03,2024-10-11 12:47:38,12.14,2024-10-07/2024-10-13,2024-09-02/2024-09-08,5
441953,64210,2019-04-03,2024-09-04 16:39:51,17.29,2024-09-02/2024-09-08,2024-09-02/2024-09-08,0